name: dart_oss_licenses
description: CLI tool that generate OSS license list of dart used in your project.
version: 0.5.1
homepage: https://github.com/ko2ic/dart_oss_licenses
authors:
  - "koji ishii <ko2ic.dev@gmail.com>"

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  tuple: ^1.0.2
  yaml: ^2.1.15
  http: ^0.12.0
  meta: ^1.1.6
  html: ^0.13.3+3

dev_dependencies:
  test: ^1.0.0

executables:
  dart-oss-licenses: main
